import Head from 'next/head'
import ConnectWallet from '@/components/ConnectWallet'


export default function Home() {

  return (
    <>
      <Head>
        <title>TRANSPARENT SUPPLY</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="author" content="raldblox" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='min-h-screen flex flex-col items-center p-4'>
        <h1 className='font-bold text-xl uppercase'>Hello</h1>
        <ConnectWallet />
      </main>
    </>
  )
}
