import Head from 'next/head'
import ConnectWallet from '@/components/ConnectWallet'
import Login from '@/components/Login'
import User from '@/components/User'
import Dashboard from '@/components/Dashboard'
import Storage from '@/components/Storage'

export default function Home() {
  return (
    <>
      <Head>
        <title>TRANSPARENT SUPPLY</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="author" content="raldblox" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='min-h-screen flex flex-col items-center p-5 lg:p-10 gap-10'>
        <Storage />
        <ConnectWallet />
        <User />
        <Dashboard />
      </main>
    </>
  )
}
